functionality:
  name: "wgd_score"
  version: "dev"
  authors: []
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--matrix"
    alternatives: []
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--scoring_mask"
    alternatives: []
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--scores"
    alternatives: []
    example:
    - "scores.txt.gz"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--plot"
    alternatives: []
    example:
    - "plot.pdf"
    default: []
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean_true"
    name: "--gzip"
    alternatives: []
    description: "Gzip output files"
    direction: "input"
    dest: "par"
  - type: "boolean_true"
    name: "--outliers"
    alternatives: []
    description: "label outliers on dosage score visualization"
    direction: "input"
    dest: "par"
  argument_groups: []
  resources:
  - type: "r_script"
    path: "script.R"
    is_executable: true
  - type: "file"
    path: "helper.R"
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "rocker/tidyverse:4.2"
  target_organization: "rcannood"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/rcannood/cmgg-structural"
  setup:
  - type: "r"
    packages:
    - "funkyheatmap"
    cran: []
    bioc: []
    git: []
    github: []
    gitlab: []
    bitbucket: []
    svn: []
    url: []
    script: []
    bioc_force_install: false
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label: []
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/rcannood/workspace/cmgg/cmgg-structural/src/wgd_score/config.vsh.yaml"
  platform: "docker"
  output: "/home/rcannood/workspace/cmgg/cmgg-structural/target/docker/wgd_score"
  executable: "/home/rcannood/workspace/cmgg/cmgg-structural/target/docker/wgd_score/wgd_score"
  viash_version: "0.6.4"
  git_commit: "595fef708a26f03f9965e141d6c07a5c6e6021c2"
  git_remote: "https://github.com/rcannood/cmgg-structural.git"
